# Generated by Django 2.2.4 on 2022-10-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arbortary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreeManager',
        ),
        migrations.AddField(
            model_name='trees',
            name='visited',
            field=models.ManyToManyField(related_name='visitor', to='Arbortary.User'),
        ),
    ]
